test(grafana): Add HTTP integration test
Signed-off-by: Bianca Petrea <biancaiulia.petrea@gmail.com>

diff --git a/.github/workflows/library-grafana10.2.yaml b/.github/workflows/library-grafana10.2.yaml
--- a/.github/workflows/library-grafana10.2.yaml
+++ b/.github/workflows/library-grafana10.2.yaml
@@ -58,9 +58,58 @@ jobs:
         path: ${{ github.workspace }}/.kraftkit/oci/digests
         if-no-files-found: error
 
+  test:
+    needs: [ build ]
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+        - plat: qemu
+          arch: x86_64
+        - plat: fc
+          arch: x86_64
+
+    runs-on: ubuntu-latest
+
+    steps:
+    - uses: actions/checkout@v4
+
+    - name: Install KraftKit
+      run: |
+        curl -sS https://get.kraftkit.sh | sh
+        echo "$HOME/.local/bin" >> $GITHUB_PATH
+
+    - name: Test Grafana functionality
+      if: matrix.plat == 'qemu'
+      run: |
+        echo "Prepare image on the new server..."
+        kraft build --plat ${{ matrix.plat }} --arch ${{ matrix.arch }}
+
+        echo "Start Grafana Unikernel in background"
+        kraft run --rm --plat ${{ matrix.plat }} --arch ${{ matrix.arch }} -M 2048M -p 3000:3000 &
+        KRAFT_PID=$!
+
+        echo "Wait 10 seconds for the web server to boot"
+        sleep 10
+
+        echo "Send HTTP request to Grafana on port 3000"
+        # HTTP status code
+        HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:3000/ || echo "000")
+
+        if [ "$HTTP_STATUS" = "200" ] || [ "$HTTP_STATUS" = "302" ]; then
+          echo "SUCCESS"
+          kill $KRAFT_PID
+          exit 0
+        else
+          echo "ERROR"
+          kill $KRAFT_PID
+          exit 1
+        fi
+      working-directory: library/grafana/10.2
+
   push:
     if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
-    needs: [ build ]
+    needs: [ test ]
     runs-on: ubuntu-latest
 
     steps:
